name: Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: cn-north-1
  EKS_CLUSTER_NAME: verislitecloud

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: cancue/eks-action@v0.0.2
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: $AWS_REGION
          cluster_name: $EKS_CLUSTER_NAME
        with:
          args: kubectl rollout restart deployment/usage-service -n verisdemo
