name: junit
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  gitpull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true
    - name: Build with Docker
      run: docker build -t 906295378353.dkr.ecr.cn-north-1.amazonaws.com.cn/litedemo/usage-managment:1.0.0 .
    - name: Push with Docker
      run: |
        docker login -u AWS -p ${{ secrets.ECR_PASSWORD }} 906295378353.dkr.ecr.cn-north-1.amazonaws.com.cn
        docker push 906295378353.dkr.ecr.cn-north-1.amazonaws.com.cn/litedemo/usage-managment:1.0.0   
  junit-test:
    needs: gitpull
    steps:
      - uses: actions/checkout@v2         
      - run: npm ci                       
      - run: npm test                     
      - uses: actions/upload-artifact@v2 
        if: success() || failure()        
        with:
          name: test-results
          path: jest-junit.xml
