name: junit
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  junit-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean test
      - name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()    
        with:
          name: JEST Tests    
          path: target/surefire-reports/TEST-*.xml 
          reporter: java-junit       
