name: 'Junit'
on:
  pull_request:
jobs:
  junit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         
      - run: npm ci                       
      - run: npm test                     
      - uses: actions/upload-artifact@v2 
        if: success() || failure()        
        with:
          name: test-results
          path: jest-junit.xml
